spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://admin-dontdothis.g.aivencloud.com:19480/defaultdb?sslMode=REQUIRED
    username: avnadmin
    password: AVNS_CTSmXN5POFWV8jcRA0L
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080

telegram:
  bot-token: 8294055596:AAF-ncqY2X1Yipq_1DebHLDaaoEQ4Ckr3sA
  #GROUP
  chat-id: -4839886352
  #SRUN
  ownerChatId: 854148566
