spring:
  application:
    name: order
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

telegram:
  bot-token: ${BOT_TOKEN}
  chat-id: ${CHAT_ID}
  ownerChatId: ${OWNER_CHAT_ID}
app:
   APP_URL: ${APP_URL}