spring:
  application:
    name: order
  datasource:
    url: jdbc:h2:file:/data/orderDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080

telegram:
  bot-token: 8294055596:AAF-ncqY2X1Yipq_1DebHLDaaoEQ4Ckr3sA
  #GROUP
  chat-id: -4839886352
  #SRUN
  owner-chat-id: 854148566
